=== GRAMCTRL/remapp.ing/public/layouts/layout_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "name": {
      "description": "Layout name",
      "type": "string"
    },
    "deviceName": {
      "description": "Exact string to match against deviceName",
      "type": "string"
    },
    "pattern": {
      "description": "Regex pattern to match against deviceName",
      "type": "string"
    },
    "viewport": {
      "description": "Viewport size",
      "type": "array",
      "items": [
        {
          "description": "Width",
          "type": "number"
        },
        {
          "description": "Height",
          "type": "number"
        }
      ],
      "minItems": 2,
      "maxItems": 2
    },
    "buttons": {
      "description": "Physical button layout",
      "type": "array",
      "items": {
        "type": "array",
        "prefixItems": [
          { "$ref": "#/$defs/button" },
          {
            "description": "X position",
            "type": ["number", "string"]
          },
          {
            "description": "Y position",
            "type": ["number", "string"]
          }
        ],
        "minItems": 3,
        "items": false
      }
    },
    "modes": {
      "description": "Mode configuration",
      "type": "object",
      "propertyNames": {
        "$ref": "#/$defs/mode"
      },
      "additionalProperties": {
        "type": "object",
        "properties": {
          "bindings": {
            "description": "Button bindings",
            "type": "array",
            "items": {
              "type": "array",
              "prefixItems": [
                { "$ref": "#/$defs/button" },
                { "$ref": "#/$defs/binding" },
                { "$ref": "#/$defs/bindingVisibility" }
              ],
              "minItems": 2,
              "maxItems": 3,
              "items": false
            }
          },
          "socd": {
            "description": "SOCD configuration",
            "type": "array",
            "items": {
              "type": "array",
              "prefixItems": [
                { "$ref": "#/$defs/binding" },
                { "$ref": "#/$defs/binding" },
                { "$ref": "#/$defs/socdType" }
              ],
              "minItems": 3,
              "items": false
            }
          },
          "additionalProperties": false
        }
      }
    },
    "additionalProperties": false
  },
  "required": ["name"],
  "oneOf": [{ "required": ["deviceName"] }, { "required": ["pattern"] }],
  "$defs": {
    "button": {
      "description": "Physical button ID",
      "enum": [
        0, "0", 1, "1", 2, "2", 3, "3", 4, "4", 5, "5", 6, "6", 7, "7", 8, "8", 9, "9", 10, "10", 11, "11", 12, "12", 13, "13", 14, "14",
        15, "15", 16, "16", 17, "17", 18, "18", 19, "19", 20, "20", 21, "21", 22, "22", 23, "23", 24, "24", 25, "25", 26, "26", 27, "27", 28, "28",
        29, "29", 30, "30", 31, "31", 32, "32", 33, "33", 34, "34", 35, "35", 36, "36", 37, "37", 38, "38", 39, "39", 40, "40", 41, "41", 42, "42",
        43, "43", 44, "44", 45, "45", 46, "46", 47, "47", 48, "48", 49, "49", 50, "50", 51, "51", 52, "52", 53, "53", 54, "54", 55, "55", 56, "56",
        57, "57", 58, "58", 59, "59"
      ]
    },
    "mode": {
      "description": "Mode ID",
      "enum": ["melee", "project_m", "ultimate", "fgc", "rivals_of_aether", "rivals_of_aether_2", "keyboard", "custom"]
    },
    "bindingVisibility": {
      "description": "Binding visibility",
      "enum": ["hidden"]
    },
    "binding": {
      "description": "Binding ID",
      "enum": [
        "a",
        "b",
        "x",
        "y",
        "z",
        "left_shoulder",
        "right_shoulder",
        "left_trigger",
        "right_trigger",
        "start",
        "select",
        "home",
        "capture",
        "mx",
        "my",
        "dpad_mod",
        "dpad_up",
        "dpad_down",
        "dpad_left",
        "dpad_right",
        "left_stick_click",
        "left_stick_up",
        "left_stick_down",
        "left_stick_left",
        "left_stick_right",
        "right_stick_click",
        "right_stick_up",
        "right_stick_down",
        "right_stick_left",
        "right_stick_right",
        "light_shield",
        "medium_shield",
        "kb_a",
        "kb_b",
        "kb_c",
        "kb_d",
        "kb_e",
        "kb_f",
        "kb_g",
        "kb_h",
        "kb_i",
        "kb_j",
        "kb_k",
        "kb_l",
        "kb_m",
        "kb_n",
        "kb_o",
        "kb_p",
        "kb_q",
        "kb_r",
        "kb_s",
        "kb_t",
        "kb_u",
        "kb_v",
        "kb_w",
        "kb_x",
        "kb_y",
        "kb_z"
      ]
    },
    "socdType": {
      "description": "SOCD type",
      "enum": [
        "neutral",
        "second_input",
        "second_input_no_reactivation",
        "direction_1_priority",
        "direction_2_priority"
      ]
    }
  }
}

=== GRAMCTRL/remapp.ing/public/layouts/gramctrl/slimsmash.json
{
  "$schema": "../layout_schema.json",
  "name": "GRAM Slim SMASH",
  "pattern": "/GRAM Slim SMASH( \\(Emulated\\))?/i",
  "viewport": [1000, 600],
  "buttons": [
    [48, 45.47, 15.66],
    [3, 0.39, 13.74],
    [2, 9.84, 9.38],
    [1, 19.49, 10.23],
    [0, 27.76, 16.3],
    [4, 21.16, 0.53],
    [32, 26.38, 39.95],
    [33, 33.07, 47.09],
    [20, 61.42, 7.03],
    [21, 69.69, 1.07],
    [22, 79.43, 0.43],
    [23, 89.17, 4.47],
    [16, 63.09, 17.26],
    [17, 71.26, 11.08],
    [18, 81.0, 10.44],
    [19, 90.85, 14.6],
    [40, 62.5, 39.63],
    [43, 59.74, 29.51],
    [44, 69.19, 32.5],
    [42, 52.95, 36.76],
    [41, 55.71, 46.88]
  ],
  "modes": {
    "melee": {
      "bindings": [
        [48, "start"],
        [0, "left_stick_right"],
        [1, "left_stick_down"],
        [2, "left_stick_left"],
        [3, "left_trigger"],
        [4, "dpad_mod"],
        [32, "mx"],
        [33, "my"],
        [16, "b"],
        [17, "x"],
        [18, "z"],
        [19, "left_stick_up"],
        [20, "right_trigger"],
        [21, "y"],
        [22, "light_shield"],
        [23, "medium_shield"],
        [40, "a"],
        [41, "right_stick_down"],
        [42, "right_stick_left"],
        [43, "right_stick_up"],
        [44, "right_stick_right"]
      ],
      "socd": [
        ["left_stick_left", "left_stick_right", "second_input_no_reactivation"],
        ["left_stick_up", "left_stick_down", "second_input_no_reactivation"],
        ["right_stick_left", "right_stick_right", "second_input_no_reactivation"],
        ["right_stick_up", "right_stick_down", "second_input_no_reactivation"]
      ]
    },
    "project_m": {
      "bindings": [
        [48, "start"],
        [0, "left_stick_right"],
        [1, "left_stick_down"],
        [2, "left_stick_left"],
        [3, "left_trigger"],
        [4, "dpad_mod"],
        [32, "mx"],
        [33, "my"],
        [16, "b"],
        [17, "x"],
        [18, "z"],
        [19, "left_stick_up"],
        [20, "right_trigger"],
        [21, "y"],
        [22, "light_shield"],
        [23, "dpad_up"],
        [40, "a"],
        [41, "right_stick_down"],
        [42, "right_stick_left"],
        [43, "right_stick_up"],
        [44, "right_stick_right"]
      ],
      "socd": [
        ["left_stick_left", "left_stick_right", "second_input_no_reactivation"],
        ["left_stick_up", "left_stick_down", "second_input_no_reactivation"],
        ["right_stick_left", "right_stick_right", "second_input_no_reactivation"],
        ["right_stick_up", "right_stick_down", "second_input_no_reactivation"]
      ]
    },
    "ultimate": {
      "bindings": [
        [48, "start"],
        [0, "left_stick_right"],
        [1, "left_stick_down"],
        [2, "left_stick_left"],
        [3, "left_trigger"],
        [4, "dpad_mod"],
        [32, "mx"],
        [33, "my"],
        [16, "b"],
        [17, "x"],
        [18, "right_shoulder"],
        [19, "left_stick_up"],
        [20, "right_trigger"],
        [21, "y"],
        [22, "right_shoulder"],
        [23, "left_shoulder"],
        [40, "a"],
        [41, "right_stick_down"],
        [42, "right_stick_left"],
        [43, "right_stick_up"],
        [44, "right_stick_right"]
      ],
      "socd": [
        ["left_stick_left", "left_stick_right", "second_input"],
        ["left_stick_up", "left_stick_down", "second_input"],
        ["right_stick_left", "right_stick_right", "second_input"],
        ["right_stick_up", "right_stick_down", "second_input"]
      ]
    },
    "fgc": {
      "bindings": [
        [48, "start"],
        [0, "left_stick_right"],
        [1, "left_stick_down"],
        [2, "left_stick_left"],
        [3, "left_stick_click"],
        [4, "left_stick_up"],
        [32, "left_stick_up"],
        [33, "my"],
        [16, "a"],
        [17, "b"],
        [18, "right_trigger"],
        [19, "left_trigger"],
        [20, "x"],
        [21, "y"],
        [22, "left_shoulder"],
        [23, "right_shoulder"],
        [40, "right_stick_click"],
        [42, "left_stick_click"],
        [43, "left_stick_up"]
      ],
      "socd": [
        ["left_stick_left", "left_stick_right", "neutral"],
        ["left_stick_up", "left_stick_down", "neutral"]
      ]
    },
    "rivals_of_aether": {
      "bindings": [
        [48, "start"],
        [0, "left_stick_right"],
        [1, "left_stick_down"],
        [2, "left_stick_left"],
        [3, "left_trigger"],
        [4, "dpad_mod"],
        [32, "mx"],
        [33, "my"],
        [16, "b"],
        [17, "x"],
        [18, "right_shoulder"],
        [19, "left_stick_up"],
        [20, "right_trigger"],
        [21, "y"],
        [22, "right_stick_click"],
        [23, "left_stick_click"],
        [40, "a"],
        [41, "right_stick_down"],
        [42, "right_stick_left"],
        [43, "right_stick_up"],
        [44, "right_stick_right"]
      ],
      "socd": [
        ["left_stick_left", "left_stick_right", "second_input_no_reactivation"],
        ["left_stick_up", "left_stick_down", "second_input_no_reactivation"],
        ["right_stick_left", "right_stick_right", "second_input_no_reactivation"],
        ["right_stick_up", "right_stick_down", "second_input_no_reactivation"]
      ]
    },
    "rivals_of_aether_2": {
      "bindings": [
        [48, "start"],
        [0, "left_stick_right"],
        [1, "left_stick_down"],
        [2, "left_stick_left"],
        [3, "left_trigger"],
        [4, "dpad_mod"],
        [32, "mx"],
        [33, "my"],
        [16, "b"],
        [17, "x"],
        [18, "right_shoulder"],
        [19, "left_stick_up"],
        [20, "right_trigger"],
        [21, "y"],
        [22, "left_stick_click"],
        [23, "left_shoulder"],
        [40, "a"],
        [41, "right_stick_down"],
        [42, "right_stick_left"],
        [43, "right_stick_up"],
        [44, "right_stick_right"],
        [50, "select", "hidden"],
        [49, "home", "hidden"]
      ],
      "socd": [
        ["left_stick_left", "left_stick_right", "second_input_no_reactivation"],
        ["left_stick_up", "left_stick_down", "second_input_no_reactivation"],
        ["right_stick_left", "right_stick_right", "second_input_no_reactivation"],
        ["right_stick_up", "right_stick_down", "second_input_no_reactivation"]
      ]
    },
    "keyboard": {
      "bindings": [
        [3, "kb_a"],
        [2, "kb_b"],
        [1, "kb_c"],
        [0, "kb_d"],
        [32, "kb_e"],
        [33, "kb_f"],
        [50, "kb_g"],
        [48, "kb_h"],
        [49, "kb_i"],
        [20, "kb_j"],
        [21, "kb_k"],
        [22, "kb_l"],
        [23, "kb_m"],
        [16, "kb_n"],
        [17, "kb_o"],
        [18, "kb_p"],
        [19, "kb_q"],
        [43, "kb_r"],
        [42, "kb_s"],
        [44, "kb_t"],
        [40, "kb_u"],
        [41, "kb_v"]
      ],
      "socd": [
        ["kb_b", "kb_d", "second_input"],
        ["kb_e", "kb_r", "second_input"]
      ]
    }
  }
}
